### ISSUE TITLE
nuc8i3能否正常使用？

### ISSUE THREAD

**Issue by recmess** [csrutil/NUC8I5BEH#1]
用的是sata接口的ssd硬盘，i3-8100，能否通用，谢谢！

**Comment by recmess** [comment]
今天装了一台，目前发现耳机孔没有输出

**Comment by csrutil** [comment]
话说系统版本是多少？

**Comment by recmess** [comment]
版本10.14.6，就是声音-选择声音输出设备，里面是空白，我是用前置音频接口输出到喇叭的。

**Comment by csrutil** [comment]
我现在使用OC引导，输出口是正常的。我找时间测试一下Clover EFI :)

**Comment by csrutil** [comment]
以后版本不对Clover进行支持，谢谢！
