### ISSUE TITLE
删除了 USB Ports Kexts，之后可以使用蓝牙 IntelBluetoothFirmware 驱动

### ISSUE THREAD

**Issue by altjz** [csrutil/NUC8I5BEH#10]
删除了 USB Ports Kexts 驱动之后可以驱动原生蓝牙 （记得 Plist.config 里面 Kernel 需要删除对应字段，否则开机报错）
删除了之后没有发现任何异常

蓝牙驱动 [IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)

或者可以参照我的 [EFI](https://github.com/altjz/NUC8I5BEH-EFI)

**Comment by MaxZ88** [comment]
因为usb定制驱动里把内置蓝牙的usb通道屏蔽了

**Comment by altjz** [comment]
> 因为usb定制驱动里把内置蓝牙的usb通道屏蔽了

删掉之后暂时没发现异常，休眠也正常，所以是不是可以理解，不需要这个？

**Comment by MaxZ88** [comment]
> > 因为usb定制驱动里把内置蓝牙的usb通道屏蔽了
> 
> 删掉之后暂时没发现异常，休眠也正常，所以是不是可以理解，不需要这个？

尽量还是使用定制usb，可以通过hackintool重新定制一下

**Comment by altjz** [comment]
> > > 因为usb定制驱动里把内置蓝牙的usb通道屏蔽了
> > 
> > 
> > 删掉之后暂时没发现异常，休眠也正常，所以是不是可以理解，不需要这个？
> 
> 尽量还是使用定制usb，可以通过hackintool重新定制一下

目前没有异常，暂时不处理了，等有什么问题再定制好了

**Comment by laijinsheng** [comment]
我按照教程去搞，系统装上了，目前就是wifi无法使用（已经按照文档修改plist配置）

**Comment by csrutil** [comment]
@laijinsheng 你在网络设置里面添加链接配置嘛？

**Comment by liuyuemozhu** [comment]
> 我按照教程去搞，系统装上了，目前就是wifi无法使用（已经按照文档修改plist配置）

蓝牙可以用了吗？

**Comment by phi-alek** [comment]
I want to use the intel bluetooth kext. i have injected it, but it doesnt do anything. looks like you have disabled bluetooth. with my clover efi the bluetooth works perfectly. so could you please open the bluetooth in your efi??? thank you.

**Comment by csrutil** [comment]
由于板载蓝牙与wifi不稳定，暂时不做集成。
