### ISSUE TITLE
一天死机一次

### ISSUE THREAD

**Issue by laijinsheng** [csrutil/NUC8I5BEH#11]
你好，我的电脑一天死机一次。以下是我的配置：

机型：NUC8I5BEH
内存：金士顿 DDR4 2333 16G
硬盘：金士顿 500G m.2接口

死机现象是直接黑屏重启，然后无法自动进入系统，需要强制电源关机重新开机

不知道啥原因

**Comment by liuyuemozhu** [comment]
我也是这个NUC，EFI也是这位作者的，内存8+8三星，硬盘500G凯侠RC，完美运行，只是不能接力，设置里面没有“允许在这台 Mac 和 iCloud 设备之间使用‘接力’”选项，奇了怪了

**Comment by laijinsheng** [comment]
会不会是因为我的硬盘有问题导致的呢？

**Comment by laijinsheng** [comment]
网上搜索了一些文章说是有些硬盘兼容性有问题

**Comment by csrutil** [comment]
我这边没有这个问题，BIOS设置的对么？出错的日志是什么呢？

**Comment by laijinsheng** [comment]
> 我这边没有这个问题，BIOS设置的对么？出错的日志是什么呢？

感谢您百忙之中的回复。

BIOS version 0077
Disable Secure Boot
Enable Legacy Boot

已设置、请问日志在哪里看呢？求答

**Comment by laijinsheng** [comment]
> > 我这边没有这个问题，BIOS设置的对么？出错的日志是什么呢？
> 
> 感谢您百忙之中的回复。
> 
> BIOS version 0077
> Disable Secure Boot
> Enable Legacy Boot
> 
> 已设置、请问日志在哪里看呢？求答



panic(cpu 0 caller 0xffffff7f82c69231): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x23 VID=0x2646 DID=0x2263
. FW Revision=S5Z42105\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5320
Backtrace (CPU 0), Frame : Return Address
0xffffff92143d39e0 : 0xffffff800031a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff92143d3a30 : 0xffffff8000454a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff92143d3a70 : 0xffffff80004465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff92143d3ac0 : 0xffffff80002c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff92143d3ae0 : 0xffffff8000319d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff92143d3be0 : 0xffffff800031a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff92143d3c30 : 0xffffff8000ac1abc mach_kernel : _panic + 0x54
0xffffff92143d3ca0 : 0xffffff7f82c69231 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController8PolledIOEhP18IOMemoryDescriptorjyy18IOPolledCompletionjPKhm.cold.1
0xffffff92143d3cc0 : 0xffffff7f82c54362 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController18RequestAsyncEventsEj
0xffffff92143d3e20 : 0xffffff8000a32329 mach_kernel : __ZN18IOTimerEventSource15timeoutSignaledEPvS0_ + 0x89
0xffffff92143d3e90 : 0xffffff8000a32249 mach_kernel : __ZN18IOTimerEventSource17timeoutAndReleaseEPvS0_ + 0x99
0xffffff92143d3ec0 : 0xffffff800035c605 mach_kernel : _thread_call_delayed_timer + 0xec5
0xffffff92143d3f40 : 0xffffff800035c131 mach_kernel : _thread_call_delayed_timer + 0x9f1
0xffffff92143d3fa0 : 0xffffff80002c013e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[28183FA3-6A50-3611-BC20-A0717B657AAC]@0xffffff7f82c46000->0xffffff7f82c88fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[5922E20B-D148-30DC-ABBA-0E99B3BE6940]@0xffffff7f8142e000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF219CC1-366A-31FC-B8ED-17C584BA2549]@0xffffff7f80d12000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D9C4809C-7B20-3663-A9C8-4DBC261AAD86]@0xffffff7f82be4000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[3581A46A-F3F3-3CE7-BA52-7046E8D66C32]@0xffffff7f81080000
            dependency: com.apple.iokit.IOReportFamily(47)[8F7948CF-5C25-33F4-A687-67F8A5B7906E]@0xffffff7f80c49000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 keepsyms=1 darkwake=0 chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
__HIB  text base: 0xffffff8000100000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 59344223598877

**Comment by csrutil** [comment]
换成最新的EFI，然后清空NVRAM试试。最后如果还没解决的话，换个SSD试试。

**Comment by laijinsheng** [comment]
> 换成最新的EFI，然后清空NVRAM试试。最后如果还没解决的话，换个SSD试试。

谢谢大佬，我一直觉得是不是硬盘有问题，我的是m.2的硬盘。非常感谢你的回复

**Comment by jyz0501** [comment]
我不是一天死机一次，是不定时死机，死机后鼠标键盘不能动，硬盘不工作，只能硬重启。有的时候是开机2分钟，有的时候是几个小时，大半天。说不准是哪个应用的问题。
同机型，硬改了94360CS2
OS: macOS bigsur 11.0.1 beta11/ Macmini8,1
OpenCore: 0.6.2
CPU: Intel® Core™ i5-8259U Processor (6M Cache, up to 3.80 GHz)
SSD: 500GB SN750    NVME.2
RAM: 16GB x 2 美商海盗船 DDR4 2666
BIOS: 0077/0083/0085 都试过
Monitor: DELL P2717H

死机崩溃日志怎么看啊

**Comment by csrutil** [comment]
Revision=S5Z42105\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5320

换个ssd试试吧。

**Comment by hekaimsbl** [comment]
> 我不是一天死机一次，是不定时死机，死机后鼠标键盘不能动，硬盘不工作，只能硬重启。有的时候是开机2分钟，有的时候是几个小时，大半天。说不准是哪个应用的问题。
> 同机型，硬改了94360CS2
> OS: macOS bigsur 11.0.1 beta11/ Macmini8,1
> OpenCore: 0.6.2
> CPU: Intel® Core™ i5-8259U Processor (6M Cache, up to 3.80 GHz)
> SSD: 500GB SN750 NVME.2
> RAM: 16GB x 2 美商海盗船 DDR4 2666
> BIOS: 0077/0083/0085 都试过
> Monitor: DELL P2717H
> 
> 死机崩溃日志怎么看啊

我有过一次这样的情况，原因是4k补丁错误，删除4k补丁或者换一个就好了

**Comment by laijinsheng** [comment]
更换ssd后就好啦 谢谢各位
