### ISSUE TITLE
设置-通用里面没有“允许在这台 Mac 和 iCloud 设备之间使用‘接力’”选项

### ISSUE THREAD

**Issue by liuyuemozhu** [csrutil/NUC8I5BEH#12]
目前我的NUC8i5BEH使用这个EFI可以使用Wi-Fi（慢速、不满速）蓝牙，想要使用接力功能发现设置-通用里面没有”允许在这台 Mac 和 iCloud 设备之间使用‘接力’”这个选项，手机只能连接NUC，但是不能使用接力，这个问题可以通过EFI进行解决吗？

**Comment by csrutil** [comment]
Intel Wi-Fi 不支持airdrop与接力。如果希望支持的话，舍弃m.2接口，换上苹果原装Wi-Fi。

**Comment by liuyuemozhu** [comment]
> Intel Wi-Fi 不支持airdrop与接力。如果希望支持的话，舍弃m.2接口，换上苹果原装Wi-Fi。

支持

**Comment by csrutil** [comment]
你的是白果网卡？

**Comment by liuyuemozhu** [comment]
> 你的是白果网卡？

不是白果网卡，是nuc自带的，我是看到远景里面的这个帖子“http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1848662”，觉得是可以支持接力的。不太清楚是我驱动没打对还是怎么回事。

**Comment by liuyuemozhu** [comment]
刚才升级了10.15.7，可以成功升级。

**Comment by csrutil** [comment]
版本升级的话应该没多大问题。我看了一下airdrop，稳定版本发布之后，我来测试一下。

**Comment by liuyuemozhu** [comment]
> 版本升级的话应该没多大问题。我看了一下airdrop，稳定版本发布之后，我来测试一下。

好的👌
