### ISSUE TITLE
风扇转得有点猛

### ISSUE THREAD

**Issue by xiankq** [csrutil/NUC8I5BEH#16]
为了用因特尔网卡，我从clover换到了您的oc，发现风扇转得比原先要猛很多，现在即便在待机状态，一样也很大声

**Comment by csrutil** [comment]
打开Activity Monitor，看是否有进程占用大量CPU

![Screen Shot 2020-10-09 at 7 51 08 PM](https://user-images.githubusercontent.com/6078291/95579913-02d09500-0a69-11eb-9e9c-f78fce91e9e9.png)

**Comment by xiankq** [comment]
可能以前用clover也这样吧，平时公司环境太吵，可能让我忽略的风扇的问题。现在使用您的oc很稳定，感谢您的回复 ，我会自己关上issue
