### ISSUE TITLE
What Works and what don't

### ISSUE THREAD

**Issue by SanjayRavindran** [csrutil/NUC8I5BEH#18]
Hi
I am planning on buying NUC8i5BEH. 
# Question.
- Can you share me what works and what don't?
- I saw you have SSDT for Type-c and also noticed you have some patches applied for thunderbolt too. Can you share me more details about Thunderbolt3 ports, whether it is working or there are some problems like sleep issue or Some random Hot-plugging issue?
- What is your experience with this Nuc-MAC-mini?

That would be really helpful. Thanks for posting your Hack in github.

**Comment by csrutil** [comment]
It works with almost everything except soldered Wi-Fi and BT.

**Comment by Tobix99** [comment]
Can confirm, use it as a daily driver with a Broadcom Wifi Chip in the m.2 slot

AirDrop, Sidecar and iMessage works (can't test Thunderbolt), but works great out of the box.

**Comment by SanjayRavindran** [comment]
Thanks for your replies.
Have anyone tried osy's [hac-mini](https://github.com/osy86/HaC-Mini/blob/master/details/thunderbolt-3-fix-part-3.md#thunderbolt-3-fix-part-3 "hac-mini") method for thunderbolt3 by flashing the custom firmware on to the TB3 chip on the NUC?

**Comment by liuyuemozhu** [comment]
This EFI that the author provides is very nice , besides AirDrop and Handoff , that's a pity.  I can use Wi-Fi and BT ,  but sometimes, I can also always use Apple TrackPad ,beautiful. oh, my version is 10.15.7, SSD : Lexar NM610 1T, memory: 16 * 2, xiede 2400, cuso 2666
in a word, That's stable

**Comment by liuyuemozhu** [comment]
Can I provide some advice which E-commerce website to buy this box to you? you can visit jd.com（京东） and tmall.com（天猫）, of course, you could download 闲鱼 app in your phone if you want to buy this box by more cheap price. Usually, it's a safe way by visiting jd.com(京东) to purchase electronic equipment

**Comment by SanjayRavindran** [comment]
Thanks for your suggestion...but NUC is on it way...

**Comment by SanjayRavindran** [comment]
Thanks for answers.. I will close the Issue

**Comment by zearp** [comment]
> Have anyone tried osy's [hac-mini](https://github.com/osy86/HaC-Mini/blob/master/details/thunderbolt-3-fix-part-3.md#thunderbolt-3-fix-part-3) method for thunderbolt3 by flashing the custom firmware on to the TB3 chip on the NUC?

Please do not flash firmwares, it is not needed and the guide you linked is for a different type of NUC; Hades Canyon, not Coffee Lake. You may brick your system if you force flash an incompatible firmware.

I don't want to spam my repo but for me Thunderbolt is working perfectly fine with ACPI patch and rename in config and security mode set to legacy in the BIOS. Tested with Thunderbolt 3 dock by me and e-gpu by others.

**Comment by SanjayRavindran** [comment]
> Thunderbolt is working perfectly fine with ACPI patch

That is really Awesome. Can you share me what eGPU enclosure you are using.
1. I would like to know whether the DRM is working with eGPU?  I am planning to buy ADT-Link R43SG-TB3. 
2. Also whether sleep works while using the TB3 with eGPU?



> Please do not flash firmwares, it is not needed and the guide you linked is for a different type of NUC; Hades Canyon, not Coffee Lake. You may brick your system if you force flash an incompatible firmware.

I haven't flashed any firmware on to thunderbolt 3 controllers but  when I was searching about the nuc hackintosh, I saw this [post](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-1640#post-2087524 "post") in tonymacx86 forum's thread so I thought that both the NUC could have same TB3 controller. 

> I don't want to spam my repo

Neither Do I. Sorry for that. I never had a hackintosh with TB3 so I was curious about that. Thanks for you reply.

**Comment by zearp** [comment]
The enclosure that was tested is Mantiz TB3. DRM should work if you use a card thats supported. Sleep will work just fine.

I checked the page you linked, it requires a flash programmer to upload a modified firmware. They don't even tell you to dump the contents of that chip and keep it as a backup before flashing it. If you just flash a modified firmware you might overwrite some unique identifiers. At least that can be the case for BIOS chips; you could lose your mac address and things like that. Without a dump of the original firmware there's no way to go back if something goes wrong.

Either way, none of that is necessary to get Thunderbolt to work on our NUCs.

**Comment by SanjayRavindran** [comment]
I totally agree.

Thanks
