### ISSUE TITLE
请问apps路径下的是放哪里的？

### ISSUE THREAD

**Issue by icedir** [csrutil/NUC8I5BEH#2]
我做了如下操作：
1、把OpenCorePkg解压后里面的文件夹复制到U盘EFI分区；
2、复制了你项目中的OC_EFI中的文件覆盖我U盘EFI分区中的对应文件夹；
apps文件夹做什么处理呢？
感谢解答

**Comment by csrutil** [comment]
apps文件夹是一些工具，可以不用理会。

**Comment by icedir** [comment]
感谢回复，请问选择Install macOS Catalina后UI一直停着没反应正常吗？大概等了20mins
对了，我使用的BIOS是0075
PS：我是使用官方安装程序制作的启动盘，不是别人做好的整合了EFI的镜像，是否有这个因素？
![image](https://user-images.githubusercontent.com/7939302/69775594-26ce1380-11d4-11ea-9f67-1943f706e5d3.png)

**Comment by csrutil** [comment]
这个我晚上回去试一下，因为我自己机器是macOS Mojave 10.14.6。

**Comment by icedir** [comment]
十分感谢！
我的操作：
1、使用官方Catalina 15.1镜像制作启动盘
`sudo /Applications/Install\ macOS\ Catalina.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume`
![image](https://user-images.githubusercontent.com/7939302/69781378-ed53d300-11e8-11ea-9023-497b6387640e.png)

2、挂载U盘的EFI分区
`sudo diskutil mount disk2s1`
然后把OpenCorePkg解压后里面的文件夹复制到启动盘EFI分区；
![image](https://user-images.githubusercontent.com/7939302/69781423-1a07ea80-11e9-11ea-86de-bc7dd8502611.png)

3、复制了你项目中的OC_EFI中的文件覆盖我U盘EFI分区中的对应文件夹；
4、插上U盘选择Install Catalina
然后就卡住了，等半小时没反应，哈哈

**Comment by csrutil** [comment]
我刚刚在我的机器上面测试了一下，发现安装界面没有问题。你有没有修改config.plist里面的序列号？

https://github.com/csrutil/NUC8I5BEH/blob/master/OC_EFI/OC/Config.plist#L672

**Comment by csrutil** [comment]
需要修改一下这三个序列号

+ MLB
+ SystemSerialNumber
+ SystemUUID

+ https://chengxuxiaohei.cn/mac-sjsm.html
+ 或者使用macserial

**Comment by icedir** [comment]
没有变更，按你的操作步骤不是应该安装后变更么？

**Comment by icedir** [comment]
我看到是安装后修改？
![image](https://user-images.githubusercontent.com/7939302/69807470-5acf2600-1220-11ea-880c-25fd16a7bf41.png)
然后确认一下，你是用的原版镜像么？

**Comment by csrutil** [comment]
有可能是这个问题，你尝试生成序列号替换之后安装。我是原版本镜像

**Comment by icedir** [comment]
好的，非常感谢你的帮助。我替换一下序列号试试~ 
你也是使用命令行生成的镜像启动盘么

**Comment by csrutil** [comment]
是的：）

**Comment by icedir** [comment]
好的，太感谢了，我再试一试 :)

**Comment by icedir** [comment]
您好，更换三码后还是不可以。
![image](https://user-images.githubusercontent.com/7939302/69808771-4d676b00-1223-11ea-8069-f4d57e003f3a.png)
请问您选择Install后大概多久开始安装界面？

**Comment by icedir** [comment]
抱歉打扰了，现在进入安装界面了，我的U盘可能读取速度太慢

**Comment by icedir** [comment]
非常感谢您的帮助！
