### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by Tobix99** [csrutil/NUC8I5BEH#20]
Hey,
Big Sur was released just now and I wanted to ask if this config is ready to update from Catalina 10.15.7 to Big Sur via the system preferences?

**Comment by csrutil** [comment]
I don't know yet, haha! I'm going to install the big Sur, and keep you updated!

**Comment by Tobix99** [comment]
Soo I just installed Big Sur on an 2nd APFS volume to Test out what works and what not 

Installation to Second APFS volume went smoothly, had to select `MacOS installer` 2 times in the Open ore Bootloader, set everything up (without Apple ID just to test).

Wifi and Airdrop worked (because of the extra WiFi card installed), but Sidecar and Streaming to my AppleTV not (maybe because of missing AppleID?)

**Comment by csrutil** [comment]
It sounds great! here is the apple said

Set Sidecar options
Make sure you're signed in with the same Apple ID on your Mac and iPad. On your Mac, choose Apple menu > System Preferences, then click Sidecar. Set options for showing the sidebar and the Touch Bar on iPad, and for using Apple Pencil.

**Comment by Tobix99** [comment]
Mhhh, will try login with my AppleIID later in the day and also check iMessage and follow up here.

~Another thing I’ve noticed is, that when the Nuc wakes up from sleep, the keyboard is not detected (on Catalina it always was detected) so I’ve to umplug and replug the keyboard to enter my password.~

Is there anything other I should test with this „extra“ system?

**Edit:** _worked, read edit 2_

Just tried to directly update to Big Sur from Catalina and had a problem at the installation (see picture)
![Log](https://user-images.githubusercontent.com/22603015/99073334-0601f800-25b6-11eb-8164-c526fc8fc5a7.jpeg)

Trying again, make sure to have a TimeMachine Backup

**Edit 2:** did a force reboot (hold the power button for 10 seconds and reboot) and this time it worked, installed all and now booted into Big Sur

**Edit 3:** Sidecar Working, AppleTV not tested yet

**Edit 4:** The "Keyboard not recognised after sleep" is not present on my upgraded system.

**Comment by Tobix99** [comment]
For me, everything is working, closing...
