### ISSUE TITLE
Paypal donate link is not working :) 

### ISSUE THREAD

**Issue by pcnoic** [csrutil/NUC8I5BEH#21]
You're doing a great job in keeping this project updated and you're saving us time and money. Please, update the paypal link so that we can donate! 

![Screenshot 2020-11-26 at 2 06 50 AM](https://user-images.githubusercontent.com/12615106/100293349-18a00800-2f8c-11eb-998a-ef5882e15430.png)

![Screenshot 2020-11-26 at 2 06 57 AM](https://user-images.githubusercontent.com/12615106/100293355-1ccc2580-2f8c-11eb-9154-304d2cd34353.png)

**Comment by csrutil** [comment]
Thank you so much! I checked my PayPal account, there is something wrong, I will update the link later🥰

**Comment by csrutil** [comment]
Hey @pcnoic, I just created a Bitcoin Address 15iEcYV1Xpr3xM4Ytyg9DCfcFwyifRFdQM, thank you!

**Comment by pcnoic** [comment]
perfect, your next beers / coffees are on me 😁 thanks for your time on
this project.
