### ISSUE TITLE
3.5 jack not support

### ISSUE THREAD

**Issue by tuanthanh0210** [csrutil/NUC8I5BEH#23]
I installed EFI in my computer, everything accepted but 3.5 jack headphone not accepted, help me. many thanks 👍

**Comment by Tobix99** [comment]
Hey, for me, the 3,5 Headphone Jack is working. But I had to restart the Mini when ever its not working.

**Comment by tuanthanh0210** [comment]
now, 3.5 is working but i must use VoodooHDA kext because AppleALC not working although i changed layout id :(

**Comment by csrutil** [comment]
3.5 is working without any issues on my side.
