### ISSUE TITLE
sudden power off after few minutes

### ISSUE THREAD

**Issue by lincolnaleixo** [csrutil/NUC8I5BEH#27]
Hi there,

After the installation (without any apparent problem) I went to use the hack but after some minutes (2-3 max) the NUC turned off. I've already tried to power off couple of times but it always turned off after some time. 

I had the 73 bios and tried every version until stoped on 83, but the error persists. I've never tried Windows on it but it seems the problem isn't on the machine itself as the macOS installation went very smooth.

Any tip on how to debug and fix this?

thanks

**Comment by csrutil** [comment]
Hey @lincolnaleixo , can you provide more detailed logs?

**Comment by lincolnaleixo** [comment]
Hi @csrutil , I installed Windows and gave up trying to use MacOS on this. Thanks for your reply
