### ISSUE TITLE
NUC8i7魔改的黑果网卡 wifi可用蓝牙不可用

### ISSUE THREAD

**Issue by Leoin1** [csrutil/NUC8I5BEH#3]
请问大佬，NUC8i7魔改的黑果网卡 wifi可用蓝牙不可用，睡眠测试都正常，0075的BIOS，第一次重启的时候蓝牙可用的，再次重启蓝牙就不可用了，还有节能的相关设置后续会增加吗？

**Comment by csrutil** [comment]
我这边没有使用苹果拆机网卡，使用的是网线连接NUC，有可能我帮助不了你。

**Comment by Leoin1** [comment]
感谢回复，期待你的后续更新～

**Comment by hmilyfyj** [comment]
我这边使用正常。你有把定制的 USBPORTS.KEXT 放进文件夹吗。

**Comment by csrutil** [comment]
@Leoin1 你有把USBPORTS.KEXT放进Kexts么？

**Comment by Leoin1** [comment]
已经解决了，问题就是没有拖入USBPORTS.KEXT，感谢!

**Comment by csrutil** [comment]
好的！
