### ISSUE TITLE
替换后升级10.15.2会进不去系统

### ISSUE THREAD

**Issue by icedir** [csrutil/NUC8I5BEH#4]
跟着你升级了0.53，进入系统后点击了系统更新，然后就进不去系统了，麻烦看下
![image](https://user-images.githubusercontent.com/7939302/70797875-6dc92500-1de0-11ea-9d65-a1d50fa48d9c.png)

**Comment by csrutil** [comment]
有替换序列号么？重置一下nvram试试

**Comment by icedir** [comment]
都有试过，进不去，我使用了NUC QQ群的包替换掉可以了

**Comment by csrutil** [comment]
有可能不支持10.15.2，我关闭issue了。
