### ISSUE TITLE
BIOS Update

### ISSUE THREAD

**Issue by Davy1992** [csrutil/NUC8I5BEH#8]
Did anyone try updating their bios above version **0075**?
Current up to date version is [0081](https://downloadmirror.intel.com/29627/eng/BE_0081_ReleaseNotes.pdf) which has a lot of great fixes, but after 0077 you cannot downgrade to 0075 anymore.

So if anyone on version 0081 or below could comment if you had any issues after upgrading I would much appreciate it.

**Comment by Beajar** [comment]
I’m on 0081 with no issues.

**Comment by Davy1992** [comment]
@Beajar Thank you!
